### ISSUE TITLE
add support Tree Shaking

### ISSUE THREAD

**Issue by damienbod** [damienbod/Angular2WebpackVisualStudio#11]

**Comment by damienbod** [comment]
https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

**Comment by robisim74** [comment]
Hi @damienbod, hi @FabianGosebrink,

I published a [new branch](https://github.com/damienbod/Angular2WebpackVisualStudio/tree/AoT-compilation) for switching to webpack 2, tree shaking & AoT compilation: #6 #8

There are many changes:
- Updated webpack configuration files
- Switched to @types: removed tsd & typings
- Created a new entry point _main-aot_ & a new tsconfig _tsconfig-aot_ for AoT compilation (used in production)
- Code cleanup

I have not used a webpack plugin for AoT compilation: there is only the plugin created by angular-cli (see this [post](http://www.michaelbromley.co.uk/blog/551/some-notes-on-angular-2-aot-mode-with-webpack-sass-ngtools)), but it still has many bugs, and it's useless: it doesn't compile, because ngc is a wrapper of tsc compiler, and to run it, you need to use the command line.

So:
- for development mode, you can use Webpack Task runner explorer, or _npm run build_ from command line;
- for production, you have to run _npm run buildProduction_ from command line (or _npm run ngc_ and then the Task).

In production, now we have only one bundle for all (app, polyfills, vendors), it is less of 1 MB:
```
dist/app.8e63cead5402bfe40814.bundle.js     959 kB       0  [emitted]  app
```
and the app is loaded in less than 800 ms:

![image](https://cloud.githubusercontent.com/assets/14012361/19614360/d2ffae6e-97f4-11e6-8c73-01c272743aae.png)

We have a reduction of about 30% than before.

I have not updated the README. Try it, and if you like it, update the README and merge it.

Greetings,

Roberto

**Comment by damienbod** [comment]
Hi Roberto

cool, thanks, I have time tomorrow morning look forward, thanks

Greetings Damien

**Comment by damienbod** [comment]
@robisim74 looks really good. I have 2 issues. The production build doesn't run, I get the following errors, any ideas?

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\damien.bowden\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'buildProduction' ]
2 info using npm@3.10.6
3 info using node@v6.5.0
4 verbose run-script [ 'prebuildProduction',
4 verbose run-script   'buildProduction',
4 verbose run-script   'postbuildProduction' ]
5 info lifecycle @1.0.0~prebuildProduction: @1.0.0
6 silly lifecycle @1.0.0~prebuildProduction: no script for prebuildProduction, continuing
7 info lifecycle @1.0.0~buildProduction: @1.0.0
8 verbose lifecycle @1.0.0~buildProduction: unsafe-perm in lifecycle true
9 verbose lifecycle @1.0.0~buildProduction: PATH: C:\Users\damien.bowden\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\git\angular2Tests\Angular2WebpackVisualStudio\Angular2WebpackVisualStudio\src\Angular2WebpackVisualStudio\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\iis express\PHP\v5.4;C:\WINDOWS\system32\inetsrv;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Windows Fabric\bin\Fabric\Fabric.Code.1.0;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\sy;C:\Program Files\MySQL\MySQL Server 5.1\bin;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\TortoiseSVN\bin;c:\Program Files\Microsoft SQL Server\120\DTS\Binn\;c:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;c:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.7;C:\Program Files\MATLAB\MATLAB Runtime\v85\runtime\win64;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GitExtensions\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Users\damien.bowden\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update2\bin;C:\Users\damien.bowden\.dnx\bin;C:\Ruby22\bin;C:\Program Files\Boot2Docker for Windows;C:\Users\damien.bowden\AppData\Roaming\npm
10 verbose lifecycle @1.0.0~buildProduction: CWD: C:\git\angular2Tests\Angular2WebpackVisualStudio\Angular2WebpackVisualStudio\src\Angular2WebpackVisualStudio
11 silly lifecycle @1.0.0~buildProduction: Args: [ '/d /s /c', 'npm run ngc && npm run webpack-prod' ]
12 silly lifecycle @1.0.0~buildProduction: Returned: code: 1  signal: null
13 info lifecycle @1.0.0~buildProduction: Failed to exec buildProduction script
14 verbose stack Error: @1.0.0 buildProduction: `npm run ngc && npm run webpack-prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\damien.bowden\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\damien.bowden\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @1.0.0
16 verbose cwd C:\git\angular2Tests\Angular2WebpackVisualStudio\Angular2WebpackVisualStudio\src\Angular2WebpackVisualStudio
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\damien.bowden\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "buildProduction"
19 error node v6.5.0
20 error npm  v3.10.6
21 error code ELIFECYCLE
22 error @1.0.0 buildProduction: `npm run ngc && npm run webpack-prod`
22 error Exit status 1
23 error Failed at the @1.0.0 buildProduction script 'npm run ngc && npm run webpack-prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run ngc && npm run webpack-prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by damienbod** [comment]
Updating npm and reseting the node_modules.
npm install npm@latest -g

**Comment by damienbod** [comment]
Just the scss build not working

**Comment by damienbod** [comment]
Hi @robisim74 
Question you removed the angular2 imports from the vendor, has does this work now, or was it not required before?

**Comment by damienbod** [comment]
HI @robisim74 @FabianGosebrink 

I've updated the docs in the dosAoT branch. Need to add something about 'npm run ngc', have to read up in this first.

The SCSS needs to be updated in the docs as well. 

Just in case I forgot to say it, the new branch, update from @robisim74 is great, thanks a million.

SCSS issue:

The styles here are not being using, I solved this issue before using require but we cannot use require with AoT. Will try to fix this, or if someone else has time or an idea, fel free.

If we cannot get this to work, I suggest we switch to plain css in the template until this is finished. 

Going for breakfast, Gruss, Tanti Saluti Damien

**Comment by damienbod** [comment]
@robisim74 @FabianGosebrink
SASS nows runs, I removed sass-loader and used different loaders.

**Comment by damienbod** [comment]
@robisim74 @FabianGosebrink
everything works, I'll merge into the master.

Maybe you could have a quick read of the readme , in case something is not so nice.

**Comment by robisim74** [comment]
@damienbod,

thanks for everything! Two things:
- I removed the Angular 2 imports from vendors because with tree shaking if you do `import '@angular/core'`, you are importing all _core_ module; instead, if you do `import { Component } from '@angular/core'` you are importing olny the _component_ class: this works only with webapack 2, and it's the reason why the bundle is smaller: don't put into it what you don't use!
- For scss files you have reason: `loaders: ["style", "css", "sass"]` is the correct order: I was doing the tests and I left the wrong one.

**Comment by robisim74** [comment]
@damienbod,

now I get this error:

```
ERROR in ./angular2App/app/app.component.ts
Module not found: Error: Can't resolve 'sass' in 'C:\Users\Roberto\Documents\GitHub\Angular2WebpackVisualStudio\Angular2WebpackVisualStudio\src\Angular2WebpackVisualStudio'
 @ ./angular2App/app/app.component.ts 12:0-31
 @ ./angular2App/app/app.module.ts
 @ ./angular2App/main.ts
```

The problem is the removal of sass-loader from the packages, but when you use this: `loaders: ["style", "css", "sass"]` you are using style-loader, css-loader and sass-loader. I think you work, because you have only removed it but not uninstalled (or you have installed it globally).

If you agree, I do a commit directly with other small changes also in the README.

**Comment by robisim74** [comment]
Ok, I created a [new branch](https://github.com/damienbod/Angular2WebpackVisualStudio/tree/minor-changes) for this.

**Comment by damienbod** [comment]
Sorry, yes I still have the package in my node_modules. Sorry and thanks

Greetings Damien

**Comment by damienbod** [comment]
Should I merge?

**Comment by robisim74** [comment]
Yes! Have you tested it?

**Comment by damienbod** [comment]
Yes, deleted the node_modules also to test, production works, will test from inside VS now

**Comment by damienbod** [comment]
dev, also, thanks
