### ISSUE TITLE
main-aot.ts references missing file

### ISSUE THREAD

**Issue by photostu** [damienbod/Angular2WebpackVisualStudio#19]
Line 7: import { AppModuleNgFactory } from '../aot/angular2App/app/app.module.ngfactory';

This file is not present in the solution.

**Comment by damienbod** [comment]
Hi @photostu 
Have you done a production webpack build from the cmdline "> npm run buildProduction"

Greetings Damien

**Comment by robisim74** [comment]
`main-aot-ts` file is the entry point for AoT compilation.

`.ngcfatory` files are created in _aot_ folder by _ngc_ compiler when you do: `npm run buildProduction`.

You can find the explanation in official documentation: https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

**Comment by photostu** [comment]
Apologies guys... still a greenhorn with this webpack stuff... Thank you for the timely response.

**Comment by photostu** [comment]
So, potential noob question still... what is the best way to get the server portion of this running as well? tsc is not a happy camper when attempting to build in VS

**Comment by FabianGosebrink** [comment]
Well tsc is the typescript compiler. If you want to get the server side running you can type

`dotnet run` on project-json level though this is a asp.net core application.

But hitting "play" in vs should work as well.

BR

Fabian

**Comment by photostu** [comment]
yeah, server side won't build cause tsc has a ton of errors...

**Comment by photostu** [comment]
some you can ignore, these show up all the time, but something is causing tsc to fail, thus breaking the build

**Comment by FabianGosebrink** [comment]
did you try `dotnet run` ?

**Comment by photostu** [comment]
yes, that works, but it runs on :5000 and webpack-dev-server will run on another port.. that's gonna be hard to get working together ;-)

**Comment by robisim74** [comment]
Ok, you're confusing a lot of things.

You should not use tsc in this project because the compilation is made by webpack. To use it, you must ensure that you have:
- TypeScript for Visual Studio 2.0.3
- TypeScript 2.0.3 installed globally

Webpack-dev-server is a in memory building. However @damienbod we have to change the port 8080 in package.json or remove it.

Greetings

**Comment by FabianGosebrink** [comment]
Just to be clear: I think @photostu is starting via Visual Studio, then Visual Studio is running the tsc and throws errors and thats why the backend from Visual Studio does not start. Did I get you right?

BR

**Comment by FabianGosebrink** [comment]
With the commit 

https://github.com/damienbod/Angular2WebpackVisualStudio/commit/8482470af767ff505e5dc367eb51bcc0ce90ae32

typescript gets not compiled anymore directly form Visual Studio. If you now start from VS it should work. If you type `npm start` it is starting the frontend (webpack-dev-server) AND the backend (dotnet run). Because we activated CORS having front- and backend on different domains/ports/servers etc. should not be a problem.

BR & HTH

**Comment by photostu** [comment]
We're getting there... get the solution clean. Run npm run start... dist folder not created.. ok, so go back and do npm run buildProduction, stuff created proper now.. now go back and npm run start... lost dist folder.

Determining this workflow for debugging is certainly not easy, I appreciate the help today for sure.
what should the expected flow be?

**Comment by robisim74** [comment]
Hi @photostu,

after the commits of @FabianGosebrink, when you do: `npm start` from the command line, you start concurrently:
- webpack-dev-server: as said, it builds in memory, and it doesn't create the dist folder: https://webpack.github.io/docs/webpack-dev-server.html
- the dotnet server

After the launch, you can browse on localhost:8080

![cattura di schermata 8](https://cloud.githubusercontent.com/assets/14012361/20092777/10a1aa8a-a59a-11e6-8ed1-2f2138208341.png)

If it still doesn't work, I think it's a configuration problem: please, let us know:
- Version of Windows
- Version of Visual Studio
- Version of TypeScript for Visual Studio
- Version of node & npm

Thanks!

**Comment by photostu** [comment]
Ok, I was still going to the 5000 port, switching over to 8080 works and produces the same output. Thanks for the assistance. I'll try not to bug you guys too much more ;-)

**Comment by FabianGosebrink** [comment]
It's the same output because on port 8080 the webpack dev server is running. Think of it as a live-reload-server "hosted" in the cache. There is no physically output. It works because the app communicates with the dotnet-core-app which is running on port 5000. There, on port 5000, the dotnet-core app is running serving from the wwwroot-folder. There we are building all the app-files in before starting the app. Thats why the content is the same.

You could also start a lite-server serving from wwwroot, having a watcher watching on the angular2app-folder, copying files to the wwwroot when changing. Would be quite the same.

Hopefully I did not make any confusion but clarified some things :)

BR

Fabian

**Comment by photostu** [comment]
Thank you for the clarification. I appreciate the explanations for sure :-)
