### ISSUE TITLE
404 errors in Edge and IE with dev build

### ISSUE THREAD

**Issue by damienbod** [damienbod/Angular2WebpackVisualStudio#29]
For the dev build, the app returns lots of 404 for map files in IE and Edge. Works on Firefox and Chrome

**Comment by damienbod** [comment]
@robisim74 @FabianGosebrink Any ideas what could be causing this?

Greetings Damien

**Comment by robisim74** [comment]
Hi Damien,

I see that problem only when Task Runner builds the app (#23), because it uses "-d" and it creates inline .map file; instead it seems to work fine also in IE & Edge from the command line with `npm run build`:

![image](https://cloud.githubusercontent.com/assets/14012361/21023048/2e2c52d8-bd7f-11e6-993a-0e2077537a52.png)

**Comment by damienbod** [comment]
webpack -d bug, cannot fix
