### ISSUE TITLE
Restoring npm packages takes a lot of time and fails

### ISSUE THREAD

**Issue by MaherJendoubi** [damienbod/Angular2WebpackVisualStudio#3]
![image](https://cloud.githubusercontent.com/assets/1798510/17643566/f3696c3e-616d-11e6-82f8-241413f9e680.png)

**Comment by damienbod** [comment]
Hi Maher

The first time it takes a lot of time. Does not fail though, this is a visual studio bug, displays npm warnings as errors and not as warnings. If you do a npm install from the cmd, this is displayed. Also the standard npm tools are required.

Hope this helps, otherwise let me know

Greetings Damien

**Comment by FabianGosebrink** [comment]
Hi Maher,
Do you mean the npm packages instead of ne nuget packages? Because in the headline "nuget" is mentioned.
You can also take a look here [#479](https://github.com/aspnet/Tooling/issues/479). Hope this helps a bit. To be sure just run the `npm install` command from commandline and do not care about the npm warning in visual studio.

Best Regards

**Comment by MaherJendoubi** [comment]
Hi @damienbod and @FabianGosebrink,

Thank you for the reply. Yes, I mean npm packages and I apologize for saying nuget packages.
I did npm install and the issue is fixed. Thanks a lot.

Best Regards,
Maher

**Comment by FabianGosebrink** [comment]
Hey @MaherJendoubi,

you are welcome. Glad we could help. Thanks a lot :)

Closing this now.

BR

**Comment by FabianGosebrink** [comment]
Maybe this can help, too

http://www.hanselman.com/blog/VisualStudio2015FixingDependenciesNpmNotInstalledFromFseventsWithNodeOnWindows.aspx

**Comment by MaherJendoubi** [comment]
@FabianGosebrink as if he saw the issue ;-). Good find! Thanks Fabian.

**Comment by damienbod** [comment]
@FabianGosebrink thanks for the link

**Comment by FabianGosebrink** [comment]
You're welcome
