### ISSUE TITLE
Update webpack production build to fulfil the max 250kb warning

### ISSUE THREAD

**Issue by damienbod** [damienbod/Angular2WebpackVisualStudio#36]

**Comment by damienbod** [comment]
Maybe consider code splitting
https://webpack.github.io/docs/code-splitting.html

**Comment by damienbod** [comment]
replaces https://github.com/damienbod/Angular2WebpackVisualStudio/issues/21

**Comment by damienbod** [comment]
@robisim74 If we separate the polyfills to a separate file (2KB), the app.bundle will be a 100KB smaller. Should we separate into 2 files, 3 HTTP requests or 2 HTTP  requests with 100KB more data.

**Comment by robisim74** [comment]
In my opinion, it's right to separate also the polyfills, but for  production we have to have only one bundle (without vendors) + one file for polyfills. I think that because without vendors the app doesn't work, so why do you have to make more http requests? Instead, polyfills serve today, but a year from now, maybe they are unnecessary.

**Comment by damienbod** [comment]
It's as you say: 

3 Requests (100KB smaller in data size for all)
app.bundle
vendor
polyfill

or (2 Requests), actual implementation
app.bundle 
vendor

Wondering if we should change to separate the polyfills or not.
