### ISSUE TITLE
Can't seem to set a breakpoint in Chrome

### ISSUE THREAD

**Issue by DOMZE** [damienbod/Angular2WebpackVisualStudio#40]
Hello,

Thank you for your template and work. It was very helpful to setup a similar solution.

The question I have is when I set a breakpoint in Chrome in the .TS files, the breakpoint never seems to be called.

Is this a feature or a bug?
I see that under the app.bundle.js, no sourcemap file is associated

Thanks!

**Comment by robisim74** [comment]
Hi @DOMZE,

it should be a problem of Task Runner Explorer: please try to use the command line: `npm run build`, and then to start debugging from Visual Studio, and it should work (if it still doesn't work, try to clean the browser cache):

![immagine](https://cloud.githubusercontent.com/assets/14012361/21429109/a6c42afc-c85d-11e6-984e-529af5ed1861.png)

@damienbod This issue is always related to Task Runner Explorer, that executes `webpack -d`. Unfortunately, at the moment this task is not updated, and it neither works well for the development nor for production. I think we should remove it.

**Comment by DOMZE** [comment]
Thank you it works!!

I did exactly what you did and went in incognito mode to make sure i had no caching and it worked!

I indeed was using Task Runner Explorer to build the project

**Comment by damienbod** [comment]
cool @robisim74 is this a problem that the webpack -d build is no use, or that the task runner does it wrong? I create an issue at webpack, but it got ignored so nothing will be fixed with the webpack -d build

https://github.com/webpack/webpack/issues/3450

Maybe we could get Mads to remove the webpack -d build and replace it with the webpack build, otherwise ye, remove the task runner. What do you think?

Greetings Damien

**Comment by robisim74** [comment]
@damienbod It looks like a _bot_ who answered you on webpack... ;)

I think we have three problems using Webpack Task Runner:
- we can not launch webpack-dev-server
- webpack-dev has the -d problem
- webpack-prod has the AoT problem (there is AoT plugin, but then you depend from angular-cli)

Yep, because Mads task was only thought for webpack, and not also for Angular & AoT compilation!

So, in my opinion, if we want avoid the use of command line for the users, we have to remove this task, and make something of different.

1. We could setup Gulp to execute the commands we need. For example, for AoT compilation, we can create a task like this:
```
// ngc compiler.
gulp.task('script:AoTCompilation', function () {

    // gulp-run: node_modules/.bin is included on the path. Supports Linux and Windows.
    return run('ngc -p tsconfig-build.json').exec();

});
```
and so on. Then, from the classic Task Runner Explorer, users could execute all the tasks they need without use the command line.

2. Another idea: we could create _our_ `AngularWebpack Task Runner`, as an extension for Visual Studio, basing on the Mads project: https://github.com/madskristensen/WebPackTaskRunner

**Comment by damienbod** [comment]
@robisim74 I think we could provide 2 or 3 solutions maybe, or at least docs.

1) cmd line
2) gulp solution 
3) AngularWebpack (maybe gulp would be enough, would be a nice project though, never tried a VS extension)

I would prefer not to have any dependencies on angular-cli

**Comment by robisim74** [comment]
1) Already implemented
2) Simple and fast: we could in the meantime give it instead to recommend the use of Webpack Task Runner
3) Me neither... we could try. See this class: https://github.com/madskristensen/WebPackTaskRunner/blob/master/src/TaskRunner/TaskRunner.cs We would need to change only the commands and names. The project is under the Apache license: I think we could do a fork, even informing Mads.

**Comment by damienbod** [comment]
Sounds like a nice project early next year. We also only need to support webpack.config.js

**Comment by robisim74** [comment]
Let me know: I can make a Gulp solution just after Christmas. Then we can study the Task Runner solution: for example, we already design it for VS 2017.

**Comment by damienbod** [comment]
Happy XMAS and thanks

**Comment by robisim74** [comment]
Happy xmas to you too!

**Comment by FabianGosebrink** [comment]
Would love to join the vs extension. This would be a really really cool project. +1 for that one! Ah: Merry Christmas to you guys :)
