### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by fahad198** [damienbod/Angular2WebpackVisualStudio#68]
I have loaded the solution in Visual Studio 2015 ... it compiles but when I run it the page comes blank

**Comment by FabianGosebrink** [comment]
Can you open the console with F12? What is written there as error?

**Comment by fahad198** [comment]
its trying to open the following location and on the console it doesnt give any error 
http://localhost:5000/index.html

**Comment by damienbod** [comment]
Have you built the SPA application?
$ npm install
$ npm run build-production

**Comment by damienbod** [comment]
Can I close this?

**Comment by fahad198** [comment]
Sorry I was off ... couldnt able to reply back ... I have used Visual studio compiler to install and build ... do u think I should have used the npm command line ??

**Comment by damienbod** [comment]
Hi @fahad198 
The npm task runner can be used to build the npm packages in VS2015, or VS2015. Pre default, this doesn't not work properly, it is configured incorrectly and you need to change this in VS. The node-sass from VS also uses 32 bit instead of 64 bit and and oly version of node. 

That's why you can check witht he command line first, and you know if the node, npm etc works. Then when this is ok, you can check fix the VS paths, node versions.

Greetings Damien
